version: 1.0.0
services:
  - mysql

variables:
  global:
    COMPOSER_BIN: $BUILD_DIR/vendor/bin
    BLT_DIR: $BUILD_DIR/vendor/acquia/blt

events:
  build:
    steps:
        # Install global packages and set global configuration.
        - setup:
            type: script
            script:
              - set -x
              - composer self-update
              - composer validate --no-check-all --ansi
              - composer install
              - source ${BLT_DIR}/scripts/pipelines/setup_environment
              - source ${BLT_DIR}/scripts/pipelines/setup_project
              - composer install-phantomjs

        # Setup behat config
        - configure-behat:
            type: script
            script:
              - set -x
              - cd ./docroot
              - ../vendor/bin/drush site-install lightning --db-url=mysql://root:root@127.0.0.1/drupal
              - ../vendor/bin/drush pm-enable lightning_dev --yes

        # Execute all testing and validation tasks.
        - run-tests:
            type: script
            script:
              - set -x
              - blt tests:phantom:launch
              - ./vendor/bin/behat --config ./docroot/sites/default/files/behat.yml --tags=3e4c4684,988f4ee4

        # Generate artifact.
        - build-artifact:
            type: script
            script:
              - set -x
              - source ${BLT_DIR}/scripts/pipelines/build_artifact
