version: 1.0.0
services:
  - mysql

variables:
  global:
    COMPOSER_BIN: $BUILD_DIR/vendor/bin
    BLT_DIR: $BUILD_DIR/vendor/acquia/blt

events:
  build:
    steps:
        # Install global packages and set global configuration.
        - setup:
            type: script
            script:
              - cd $BUILD_DIR
              - composer self-update
              - composer validate --no-check-all --ansi
              - composer install
              - source ${BLT_DIR}/scripts/pipelines/setup_environment
              - source ${BLT_DIR}/scripts/pipelines/setup_project
              - composer install-phantomjs

        # Install Lightning and copy prod database.
        - install:
            type: script
            script:
              - cd $BUILD_DIR/docroot

              # Install Lightning from scratch first so our settings file gets
              # the correct DB connection details for the test env.
              - /usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ../vendor/bin/drush site-install lightning --db-url=mysql://root:root@127.0.0.1/drupal --yes

              # Then copy the prod database over.
              - ../vendor/bin/drush --alias-path=../drush sql-sync @speedrun.prod default --yes
              - ../vendor/bin/drush updatedb --yes
              - ../vendor/bin/drush cache-rebuild

              # Run a config import to get any new config changes from code.
              - ../vendor/bin/drush config-import --yes --config=../config/default

        # Generate behat config
        - configure:
            type: script
            script:
              - cd $BUILD_DIR
              - ./vendor/bin/drupal behat:init http://127.0.0.1:8080 --merge=../docroot/profiles/contrib/lightning/tests/behat.yml
              - ./vendor/bin/drupal behat:include ../docroot/profiles/contrib/lightning/tests/features --with-subcontexts=../docroot/profiles/contrib/lightning/tests/features/bootstrap --with-subcontexts=../docroot/profiles/contrib/lightning/src/LightningExtension/Context
              - ./vendor/bin/drupal behat:include ../docroot/tests/behat/features

        # Execute all testing and validation tasks.
        - run-tests:
            type: script
            script:
              - cd $BUILD_DIR/docroot
              - ../vendor/bin/drush runserver --default-server=builtin 8080 &>/dev/null &
              - ../vendor/bin/phantomjs --webdriver=4444 > /dev/null &
              - sleep 10
              # Run a specific Lightning test:
              # - Panelizer is enabled for landing pages (1e244c89)
              - pwd
              - ../vendor/bin/behat --config ../sites/default/files/behat.yml --tags=1e244c89

        # Generate artifact.
        - build-artifact:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/build_artifact

        # Deploy the build artifact to a Cloud on-demand environment.
        - deploy:
            script:
              - pipelines-deploy

  # When a GitHub pull request is merged, this deletes the corresponding ODE.
  pr-merged:
    steps:
        - deploy:
            script:
              - pipelines-deploy

  # When a GitHub pull request is closed, this deletes the corresponding ODE.
  pr-closed:
    steps:
        - deploy:
            script:
              - pipelines-deploy
ssh-keys:
  drush-key:
    secure: 2acyuc5BzrCLGCH4A9X26faHhhmCUlUvtc1EQC8sjSYHXDWh1grPdMtlTbvTq0Qz11Hl1VbPeMbqjB6bsD6j/eIP9Z6vqOHZXPHQLJvjD4yhZg7THmqBZZqJSuNRJwuvPunGBgplCZlNcHULlJaNg7ZYKNsRwMRQaRrBxrt/rGQEaVBcC32lP+PmYh6sT8stqdxyKqs90HNxSsqsXjfE5Ww1Dcp3Joaz2sdFIkXCCJ1YGZR+aszsVUwNkBY06S/raukJbWsKAU4xr+l9GTgIRZjcqY6c1wZnvqc3GO5w1GZAOgrWxlhPK7hYOv7KSQQ2Ga2kGfqfqAa9nuCOWhjbFp5Mu0kqty9DiGk95hqA817s+VwINb8rjnCaZy2qFs9ovqFRSSkGCUO/DFyKuqW8C2rgLw0sxlMd4D+1iLIxtQve0+gE3zEaDjv7d15u31ZLcOEjfV/YTTyvdrWLhZRpmXIwTr+ZotDDGT++ESxHoGxQAf35ZRkJDPrN9bBGKI1A8iKbJybRaw+Myliny/kl4QPd/1Q4ZbnYwSS9K9m4YnE9LV7IqGtNAVGo1QjiCr1tqCRneGmC3tUUQScYBZbUBPV9wDUwDQWtZLiHiaeWAl2XI5u6/5ZTZYNIukl5nR5s6CmCG4zeiRpHluX07j7TazfxRQo6g8T/utUCnV5NyFs3vw=J5MwtyhASU0OTtIBAGe6BJg91sztkRim3iGdN8F/QNEi5jFK5WZl1o59M7HgafWkwypoVH5pHLo4ok3cG8m/r1LvNN2rOByjGvSTXYr9kNqLbHhOpDUq/Lde+mpqvApmV17/2HywECakyp12hm+DhQHJjfezRGTShkFkeK0GPIhtOxSjM0GTclTqlcc4ka/ns0aEyXDxmqO93rXNyIYd3XNH2WNlnYgokktTgNF8tnsnd+hnxHc/S2J4CxJkLgghaZS/eQeXU5ImDqpQJSasT9fV3tBcWvaw5D9MZUXb5mmvduWmlwQc3JlCL/9kEYmXnZVuAVQ4lrh2mS5Yo+mAoXyg+KPo+VJP9GDiim0czyAjHMwKwSw3U11k98yVwpAz3LwrT7K6E8wMRvwKC/otp62T21t+15VHR08dPSacw59yuNmhHzdyrzszEwHpdkWxtZLLmtORfGaYNzC9SKk7jnGDjlT+KuJOMsr7IqvMeOGMxzsszraxoMaigd+UOHVd1HoWOQqLK+5k1ns6/ZtPUqxEmabrMnxYkc9Xr97xTInHFQsehiP9828AdbJrp0zBABEne6gaKAbyVhOdgVZnQo7ctvE5SU2KYeeMFCJZh5LJbUyVvhDT5W1sIs9ZoTwc8CdV0TE29JV7Ts16RRAGgJBY9U+iCzcbrNDtlTvjYEQY1YAuSdOgsGoutCom7Cy+8txCDuwJhAfE5N23uI8mzO3HAtVU+qc0mBV1ee1CRcuAhH+AFd5ZpurrLR3RBqAPOy33awIZUlTWtSGWFEQb79l8RqCY2cI1JccfAFOh2KEtHywLrsvOypyA0Wf7lpqnEjtcmQZWQp8bRa1wMr6ZapNQgFxujGH5bkjg/7RvdXkNKS04fK6PxyOwovwTLPDyou/MV8FSOChcXdaZFjgi6r3wHZOa3Or0NxjqbmYLsFe7P9wSIhAkvaPqTFY1ZQXGvWdur5FyeyEzZHzVvJPrnpzu6QZTFmcyTJvrtJ/3gZ0XT1X8kTd6MEE2hbevBl347D2VVaaoDCBsJznWzl04zz9SxTl6rmIivOKOUfGkuZ0a7BKirtxgXWZnwJDn/t7gVaxUwtLkgK9DVIjrG5gliCskeyUxJf03jNNoRTTCt9RztulF3HKnOnxVr3IUtQ3KT+u9lSpQSr69/slL+6CbfL87bxUdQ/fh4lggqF8Iaby/E4EUwmJQLkumT0x7sjkmszLoZWEZNAq9Y411cyIqItPwKtk9jhNjRwcakHIG1mu3drsVurFMH1ltUAy+WNjFm3c7qNvaYiGRQLtjaD2ndgFDnR9gkantoE5as2iWnfFcfDrya+tdv5Z9mVWBMW6kPz1A1yfhWCFXN7uTJ6pEl+itdhMtywXFb/fnj9kPbT1CAedu0UvonjLnNHmKx1wnCJIcuYCTKo9lDjwOKjgQQl+OlfxKwRjbP4+2QGSOlvEd8HaTjtf/adSkXzD1CQ6d56A9Pwzbg57n6v1O5Y7Wm2+i3m2d21oIopXKCSY0oRyV4R+Ee8I3d14gYYKlkF9Oq6aTV0DqtdFebC2K1fRxk7sIKzaob/iZZgTaEpoyArsTpGHkV7ZGkr9q2tXZ510xStCHN0K17A4n7eh2wZPx2Eg6f+wXDuyANJ+EFH9hUCIUwwuN6GXnA7pjOr5OZRxzu32HSu8MYvlz+xLwCicQsnLCWN8p7bYzFIcal14mSmlxuxGWuv4zzjzwhWKmaTp/n3nvZ4vduWWTdfu4PVb0JMKf3EF6ZXehhMdmMryBxRwt7Mnk1C9sD7vINDRTPUCH7B6xcE5OyrE4DnNlicyodRJ4O+oKZLNKmdZbM9l2KP5A0FMGsOCDpNw0ADQtJgHUNEJjExun6ZQlvR8MxjX80RAf0eULawj318MYaFKeOeC5Hpv645mImhWEWjfPeY8ipWzyzxLhrDYEphbh3sCCjfGeqcsOzeIhlVt5GmLBtqPtG6vmmfw9A00fqRGQPyqglHlvdjDYdpv0QhIy5T306KJPo5Kw9jWHAkkTMSbDnt2JnTTpMCvuKlCFYaMk24m4XsR0ol2VnmmcpD5IDKjtt5JqilysteuW/n92+Y9B3dEgXsU1h3QIF/cV6NBN1BHcqHgB6lVAC2wbBb+n36cWP6pCUzeIiMCPavw3iPVTlsgqWZnWRxU8KUWC2OPIWRF5J+mUNY3xAeN1pTofuGbn6kF6+8y/SNA2yeuOwmOGiklYdIAf17RKoNMcR6iCdUuobChUqeLwRFPJfJN3rEPCRuXOdqMM5pfBBicjAJ+sTfbRY9Bjs5z98qBJZ2By+2R1QhAb7XmOvaEG+NkHNNumRpzau8dVko9ESaZuYGcoM6iENEjMIcRHClsXytLT77qWitR0TvA+oBEYCtTutOQgjKPwv0E0rOgnGPRmZOPrQiiUWWGMCMoej4duZuUQBZbvYh4oWDn4T8XtxtyjDndaVStTDfWVrOLZ6m2mXNTxe5qYTxXZSuxium4u+O+wlFySLVTjKiyJtH2asZ38M0q6+hfi/uSbf4hGcECkXhZi/e1mlfnXyKV2XzNuKwEPT0LB59z3xx1ofTy8ov2nGs1OCZ8lBImaCrjtkd6wDXliOKsZMQ0FAIRCAX1z3XOSXZ4WgIXY8xXPQlKrk5yobgKs2Adzrtl+loQ/JpPQIBVKaSP6QWYQaUSgBqe+IpVy5hDJnknDcJy1xELOBYnoIwkTGT2UQ89/NzL+kbSrjA0SmIaRHlI58ekM7zOJq8yZMRKnZ+wfP6r14/nhZnIiFS/tsXyiugFt1jgnwvwwDhmia6yaLShCDQiCkagfne3KIvcspcTfnndjAe4cytvKxNBp6cbd9OTSoBXxmoHFvfjxCM05X+wbKiPCHV9BS1NOM050eesgviHFwgySeO87BBZPg6mxcp/NxizUrnZcDhcwlceozzgnyrYaXsPcBsJay5n7bZSirTxzgrT5LenVTYEQ9E2uw8r+xhSDlGeIQ6XIENqT3Sq9CrwMys00PzreDDmyhBgOlwwEjbHlmNTZd2eNhDEd6XmigJo4bGuVYMLDZUIj9AiyBvlCOupZ/CMpvLQfTvaHG99lxnCggW58HJoQjBlALxLS/PVBxAftTzwW7r3MWNyucBvnt0HK85uF+eaF9Onk1t1vZlhcFHt5zUQoVf3ZEW5jNYouwiou7GhCctj9ouYU/Sj74z7XsYwyNjzXjwz37OfHAnlIZbopXJDInWW/Mr7hWRdNJSvUVCcNeHi0qqR8Px0uNPTohm8NujAUOL3FL3EoFxMa5/RNr/RiR9DBE6IYtc2fOdDthHUKiMHbObCLEj2Ntk0omaH5wOJsHmzFiCaqP0wfqsNtx/1WWWeOq9VtW0lEoE3g7etzSK0lXFLyIB9vEASsZbrN7gd2igCDyh55iFzK6mR9jbvDB+uJWeoO4wIHg2urqFv1N9LYhDB3cdsHExGvkHPapczmrBE9rKxkd3WsuYZ2T3sdJT7jQ8aKUCYBmeJj8oj28o5JrUp2Li1XrqHVc/phz8sCsMt9XC6W6VsurmJ5um9Ax8JitK9R+uMIp4NfxRYJohmIyRJICeFnaMvgpfaPlttdUOcBSY8b4F66BzxE52QhdWwDPWp+YlE0xjoAZwy6c8LFqY1gun9A8SAoTtd8Gb9OlrJmWfk7sYnSugrWBkiApNE7oc7cdYMfZiyI4J27brNvdOgMths0w5ZH//e+/cLYzCx3akpboz/PyF8xouuaGwKMWXP6gBPw8EiNxC1rRqVcmWEBYEJLHXWDRBD9bpyrMSdRIL+GsYk9HOWAU0a18MPM9jSaJI46baozo71oTChVoyudE4odY+YRI8rz+AIYDENxp0OwIDTtLUclHn9s69LzM3Z9o2WISheQPNrFXZ+nLNwKiXM29gNDQEc8OKmTvmLEEWQndDFjFjz0Jcc+t8p2b7A/VrRhMj/9JSUXrolamLrtlmNOzigXcEHe33m8lP7hl3abVwm7y3ErRqtAjENKMGVWVMFz1vEAVSOjIgwm05dM551mTW2yet8jZJzPTJg0TDbNZ/DeLlPIMnq9zNb7BF1GiA2RXKlNi8XmB/XyiGHkFimm8rod4P8QLCQsR9OQ6luDb2NwBT1iGtc3Qmyq2HZz7oO8tmwm/uXAq5e+9uqka4kWNsSNSECU/WUbURGF5rPPnAZZHQqPGKWzmviSZzbBtQTN2SBqC74vLcbRdizcErqF2xHUXK0HioC6Z/JZpni7nPuknX5tF2Cpld2232W+uzFfXbQ4Q3uZodBhCm+S0UZleyXbEJ7HO4yqX/idL6abItVDzb87MDU/wXMhrmbSVaIwpjLDF3f9qFvF5YfxUwFVrwTazVsn5epOOjh8sOQnFaZ+hFA3YJbxFBTTtLSHoPJ+8NAP41o8NTn/5OGDOucLbZBtXNgAwC6KvEYLyYX/E3wgbG+pB/LtfIPtcXLwiP7kl6iCieCRzKrfoPoAA2L1+aEsedgmFBV+lC6qkHCH2+keng77TddnQA/h4B4l52a8zgU2FC79wyN9H5pYbY1o2MVtHupybCLnV0dogZFmXzEMtpIHdSaePQ==
